<h1>Vegaupplýsingar</h1>
<script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
<script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.2.4"></script>
<div id="map" style="width: 100%;height: 700px"></div>
<p><strong><em>Gögn fengin frá Vegagerð Ríkisins &copy;2015</em></strong></p>
<script>
  var map = L.map('map',
    {
      center: [65.10418, -19.0],
      zoom: 7,
      maxZoom: 11,
      minZoom: 7
    });

  var mainLayer = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(map);
  var watercolorLayer = new L.StamenTileLayer("watercolor");

  <?php foreach($this->signs as $sign) : ?>
    var <?=$sign->sign_url . "_sign";?> = L.icon({iconUrl: '<?="road-info/icon/" . $sign->sign_url . '.gif'; ?>', iconAnchor: [16,16], popupAnchor: [0,0]});
  <?php endforeach; ?>
  /**
   * Loop through the weather stations and create a dynamic variable for each and one.
   * Then add those variables into an array for later use
   */
  var weatherStations = [];
  <?php foreach($this->weatherStations as $weatherStation) : ?>
    <?php $markup = "<p><strong><em>Upplýsingar frá: " . strftime('%d.%m %Y %H:%M',$weatherStation->date) . "</em></strong></p><h2>Veðurupplýsingar</h2><ul><li>Hæð yfir sjávarmáli: {$weatherStation->height}m</li><li>Daggarmark: {$weatherStation->dew_point}°C</li><li>Loftþrýstingur: {$weatherStation->airpressure}hPA</li><li>Hitastig: {$weatherStation->temperature}°C</li><li>Veghiti: {$weatherStation->road_temperature}°C</li><li>Rakastig: {$weatherStation->humidity}%</li><li>Vindur: {$weatherStation->wind_direction_asc} ({$weatherStation->wind_direction}°) {$weatherStation->wind_speed} m/s (hviður allt að {$weatherStation->wind_gust} m/s)</li></ul><h2>Umferðarupplýsingar</h2><ul><li>Umferð sl. tíu mín: {$weatherStation->traffic_last_ten}</li><li>Umferð frá miðnætti: {$weatherStation->traffic_accumulated}</li></ul>";?>
    weatherStations.push( <?="segment_" . $weatherStation->segment_id . "_weatherstation"; ?> =
      L.marker([<?=$weatherStation->latitude . ", " . $weatherStation->longitude;?>]).bindPopup("<h1><?=$weatherStation->name;?></h1><?=$markup;?>"));
  <?php endforeach; ?>
  var weatherStationsLayer = L.layerGroup(weatherStations);

  var segments = [];
  var signs = [];
  <?php foreach($this->segments as $segment) : ?>
    var <?="butur_" . $segment->segment_id;?> = [];
    <?php foreach($segment->segmentParts as $segmentPart) : ?>
      <?php $segmentName = "butur_" . $segmentPart->id_butur . "_obj_" . $segmentPart->object_id . "_vegur_" . $segmentPart->nr_vegur . "_kafli_" . $segmentPart->nr_kafli; ?>
      var <?=$segmentName; ?> = L.geoJson({
          "type" : "LineString",
          "coordinates" :[
            <?=$segmentPart->pattern;?>
          ]
        },
        {style: {"color": "<?=$segment->line_color;?>"}}
      ).bindPopup("<h1><?=$segment->name_long;?></h1><h2><?=$segment->name_short;?></h2><?=$segmentName;?><p>Ástand vegar: <?=$segment->condition_long;?>");
      segments.push(<?=$segmentName;?>);
      <?="butur_" . $segment->segment_id;?>.push(<?=$segmentName;?>);
    <?php endforeach; ?>
    <?php if(sizeof($segment->signs) > 0) : ?>
      <?php foreach($segment->signs as $sign) : ?>
        var <?="skilti_" . $segment->segment_id;?> = L.marker([<?=$sign->center_lat;?>, <?=$sign->center_lng;?>], {icon: <?=$sign->sign_url . "_sign";?>}).bindPopup("<?=$sign->name;?>");
        signs.push(<?="skilti_" . $segment->segment_id;?>);
      <?php endforeach; ?>
    <?php endif; ?>
  <?php endforeach; ?>
  var countryLayer = L.layerGroup(segments).addTo(map);
  var signsLayer = L.layerGroup(signs).addTo(map);

  <?php foreach($this->routes as $route) : ?>
    var <?="route_" . $route->short_name; ?> = [];
    <?php $routeArr = array();?>
    <?php foreach($route->segments as $segmentPart) : ?>
      <?php $routeArr[] = "butur_" . $segmentPart->segment_id;?>
    <?php endforeach; ?>

    var segmparts = [];
    <?php foreach($routeArr as $arr) : ?>
      <?=$arr;?>.forEach(function(element,index){
        segmparts.push(element);
      });
      if(typeof <?="skilti_" . substr($arr, 6);?> !== "undefined"){
        segmparts.push(<?="skilti_" . substr($arr, 6);?>);
      }
    <?php endforeach; ?>
    <?="route_" . $route->short_name; ?> = L.layerGroup(segmparts);
  <?php endforeach; ?>


  L.control.layers({
    "Venjulegt" : mainLayer,
    "Vatnslitakort" : watercolorLayer
  }, {
    "Allt landið" : countryLayer,
    "Veðurstöðvar" : weatherStationsLayer,
    "Skilti" : signsLayer,
    <?php foreach($routes as $route) : ?>
      "<?=$route->long_name;?>" : <?="route_" . $route->short_name;?>,
    <?php endforeach; ?>
  }).addTo(map);
  L.control.scale().addTo(map);

</script>