<?php echo $this->doctype(); ?>
<html lang="is">
    <head>
		<meta charset="utf-8">
		<?= $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>
		<meta name="msapplication-TileColor" content="#292468">
		<meta name="msapplication-TileImage" content="<?=$this->basePath("favicons/mstile-144x144.png");?>">
		<meta name="theme-color" content="#292468">
		<?=$this->headTitle('RoadInfo ')->setSeparator(' / ')->setAutoEscape(false) ?>
		<?=$this->headScript();?>
        <?=$this->headLink(); ?>
			<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
			<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    </head>
	<body>
		<?=$this->content; ?>
		<?=$this->inlineScript() ?>
	</body>
</html>
